height_map_node:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    topic_cloud: /cloud_registered
    resolution: 0.05
    big_width: 400
    big_height: 400
    shift_thresh_m: 0.5
    max_height: 2.0
    z_min: -10.0
    z_max:  10.0
    drop_thresh: 0.07
    min_support: 4

    sub_width: 200
    sub_height: 200
    sub_resolution: 0.05
    publish_rate_hz: 10.0

    occluded_fraction_threshold: 0.5
    voxel_downsample: false
    voxel_leaf: 0.05
    transform_cloud: true
